name: KillTracker
version: 1.0.0
main: com.jinzo.KillTracker
api-version: 1.16
# folia-supported: true

commands:
  killtracker:
    description: Root command for KillTracker plugin
    aliases: [kt]
    permission: killtracker.use
    permission-message: You do not have permission to use this command.

permissions:
  killtracker.use:
    description: Allows use of /killtracker base command
    default: true
    children:
      killtracker.reset: true
      killtracker.show: true

  killtracker.admin:
    description: Allows use of admin commands
    default: op
    children:
      killtracker.change: true
      killtracker.reload: true
      killtracker.set: true
