name: Discord Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          contentType: 'application/json'
          body: |
            {
              "content": "**New commit pushed!**\n**Message:** ${{ github.event.head_commit.message }}\n**URL:** ${{ github.event.head_commit.url }}"
            }